"""empty message

Revision ID: ebb7e72b4047
Revises: 
Create Date: 2020-11-21 15:04:48.130913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb7e72b4047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usersv2_username'), 'usersv2', ['username'], unique=False)
    op.drop_column('usersv2', 'isAdmin')
    op.drop_column('usersv2', 'customerId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersv2', sa.Column('customerId', sa.INTEGER(), nullable=True))
    op.add_column('usersv2', sa.Column('isAdmin', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_usersv2_username'), table_name='usersv2')
    # ### end Alembic commands ###
